## Basic Configuration
baseURL = "https://co6ted.github.io/"
languageCode = "ja"
title = "co6ted's info"
publishDir = "docs"
theme = "hyde-hyde"
hasCJKLaunguage = true

## Site Setting
[params]
  themeColor = "theme-base-09"
  postNavigation = false
  highlightjs = true
  highlightjsstyle = "github"

  ## sidebar, copyright
  authorimage = "/images/co6ted.png/"
  #description = "技術者してます"
  sidebarImage = "co6ted.png"
  copyright = "Komuro Yuta"

  ## GoogleAnalytics
  # googleAnalytics = ""

## Social Accounts
[params.social]
  title = "Social Accounts"
  github = "co6ted"
  linkedin = "co6ted"
  twitter = "co6ted"
  facebook = "co6ted"

## Main Menu
[[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"
[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about/"
[[menu.main]]
  name = "Resume"
  identifier = "resume"
  weight = 200
  url = "/resume/outline/"
[[menu.main]]
  name = "skills"
  identifier = "skills"
  weight = 300
  url = "/skills/skill/"
[[menu.main]]
  name = "Links"
  identifier = "other"
  weight = 400
  url = "/other/link/"
