## Basic Configuration
baseURL = "https://co6ted.github.io/"
languageCode = "ja"
title = "co6ted's info"
publishDir = "docs"
theme = "hyde-hyde"
hasCJKLaunguage = true

## Site Setting
[params]
  #author = ""
  #title = ""
  #authorimage = ""
  #datefformat = ""

  # sidebar, copyright
  copyright = "Komuro Yuta"
  showBuiltwith = true

  highlightjs = true
  highlightjsstyle = "github"

## Social Accounts
[params.social]
  github = "co6ted"
  linkedin = "co6ted"
  twitter = "co6ted"
  facebook = "co6ted"
  email = "co6ted@gmail.com"

## Main Menu
[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about/"
[[menu.main]]
  name = "Resume"
  identifier = "logs"
  weight = 200
  url = "/logs/resume/"
[[menu.main]]
  name = "skills"
  identifier = "skills"
  weight = 300
  url = "/skills/skill/"
[[menu.main]]
  name = "Links"
  identifier = "other"
  weight = 400
  url = "/other/link/"
