## Basic Configuration
baseURL = "https://co6ted.github.io/"
languageCode = "ja"
title = "co6ted's info"
publishDir = "docs"
theme = "hyde-hyde"
hasCJKLaunguage = true

## Site Setting
[params]
  themeColor = "theme-base-09"
  postNavigation = false
  highlightjs = true
  highlightjsstyle = "github"

  ## sidebar
  authorimage = "/images/co6ted.png"
  sidebarImage = "co6ted.png"
  ## copyright/Licence
  copyright = "Komuro Yuta"
  license = "MIT"
  licenseURL = "https://github.com/co6ted/co6ted.github.io/blob/source/themes/hyde-hyde/LICENSE.md"
  showBuiltWith = true

  ## GoogleAnalytics
  # googleAnalytics = ""

## Social Accounts
[params.social]
  title = "Social Accounts"
  github = "co6ted"
  twitter = "co6ted"
  facebook = "co6ted"

## Main Menu
[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 100
  url = "/about/"
[[menu.main]]
  name = "Logs"
  identifier = "logs"
  weight = 200
  url = "/logs/"
[[menu.main]]
  name = "skills"
  identifier = "skills"
  weight = 300
  url = "/skills/"
[[menu.main]]
  name = "Links"
  identifier = "other"
  weight = 400
  url = "/links/"